# Bible Bowl Configuration Properties
# 
# This file is loaded by the biblebowl CLI.
# Local changes in this directory take precedence over global settings in ~/.tbb/bible-bowl.properties.

# The default study set to generate when no study set argument is specified on the command line.
# (e.g. acts, luke, josh-judg-ruth)
#default-study-set=acts

# The date stamped on covers and footers (format: YYYY-MM-DD).
#test-date=2027-04-03
